#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  basic:

services:
  ca.kisa.com:
    image: hyperledger/fabric-ca:x86_64-1.0.0
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.kisa.com
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/org1.kisa.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/a22daf356b2aab5792ea53e35f66fccef1d7f1aa2b3a2b92dbfbf96a448ea26a_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.kisa.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.kisa.com
    networks:
      - basic

  orderer.kisa.com:
    container_name: orderer.kisa.com
    image: hyperledger/fabric-orderer:x86_64-1.0.0
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./config/:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/kisa.com/orderers/orderer.kisa.com/:/etc/hyperledger/msp/orderer
        - ./crypto-config/peerOrganizations/org1.kisa.com/peers/peer0.org1.kisa.com/:/etc/hyperledger/msp/peerOrg1
        - /etc/localtime:/etc/localtime:ro
    networks:
      - basic

  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb:x86_64-1.0.0
    ports:
      - 5984:5984
    #environment:
    #  DB_URL: http://localhost:5984/member_db
    #volumes:
    #  - ./persistence/couchdb0:/opt/couchdb/data
    networks:
      - basic

  peer0.org1.kisa.com:
    container_name: peer0.org1.kisa.com
    image: hyperledger/fabric-peer:x86_64-1.0.0
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org1.kisa.com
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.org1.kisa.com:7051
      # # the following setting starts chaincode containers on the same
      # # bridge network as the peers
      # # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
    #    - ./persistence/peer0:/var/hyperledger/production
        - ./crypto-config/peerOrganizations/org1.kisa.com/peers/peer0.org1.kisa.com/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/org1.kisa.com/users:/etc/hyperledger/msp/users
        - ./config:/etc/hyperledger/configtx
        - /etc/localtime:/etc/localtime:ro
    depends_on:
      - orderer.kisa.com
      - couchdb0
    networks:
      - basic

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb:x86_64-1.0.0
    ports:
      - 6984:5984
    #environment:
    #  DB_URL: http://localhost:5984/member_db
    #volumes:
    #  - ./persistence/couchdb1:/opt/couchdb/data
    networks:
      - basic

  peer1.org1.kisa.com:
    container_name: peer1.org1.kisa.com
    image: hyperledger/fabric-peer:x86_64-1.0.0
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.org1.kisa.com
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer1.org1.kisa.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.kisa.com:7051
      # # the following setting starts chaincode containers on the same
      # # bridge network as the peers
      # # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
        - /var/run/:/host/var/run/
    #    - ./persistence/peer1:/var/hyperledger/production
        - ./crypto-config/peerOrganizations/org1.kisa.com/peers/peer1.org1.kisa.com/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/org1.kisa.com/users:/etc/hyperledger/msp/users
        - ./config:/etc/hyperledger/configtx
        - /etc/localtime:/etc/localtime:ro
    depends_on:
      - orderer.kisa.com
      - couchdb1
    networks:
      - basic

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:x86_64-1.0.0
    tty: true
    environment:
      - GOPATH=/opt/gopath:/opt/gopath/ext_lib
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.kisa.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.kisa.com/users/Admin@org1.kisa.com/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - ./config:/etc/hyperledger/configtx
        - ./crypto-config/peerOrganizations/org1.kisa.com/users:/etc/hyperledger/msp/users
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/kisa
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - $GOPATH:/opt/gopath/ext_lib
        - /etc/localtime:/etc/localtime:ro
    networks:
        - basic
    #depends_on:
    #  - orderer.kisa.com
    
